-- ============================================
-- CUSTOMER RETENTION & RFM ANALYSIS PROJECT
-- Tool: PostgreSQL
-- ============================================



-- ============================================
-- 1. VIEW CUSTOMER DATA
-- Purpose:
-- Inspect customer information and unique customer IDs
-- ============================================

SELECT *
FROM olist_customers_dataset
LIMIT 10;



-- ============================================
-- 2. VIEW ORDER DATA
-- Purpose:
-- Explore order purchase dates and order IDs
-- ============================================

SELECT *
FROM olist_orders_dataset
LIMIT 10;



-- ============================================
-- 3. VIEW ORDER ITEMS DATA
-- Purpose:
-- Inspect product prices and order item details
-- ============================================

SELECT *
FROM olist_order_items_dataset
LIMIT 10;



-- ============================================
-- 4. CUSTOMER ORDER FREQUENCY
-- Purpose:
-- Calculate how many orders each customer placed
-- ============================================

SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC;



-- ============================================
-- 5. CUSTOMER MONETARY VALUE
-- Purpose:
-- Calculate total revenue generated by each customer
-- ============================================

SELECT
    c.customer_unique_id,
    SUM(oi.price) AS total_spent
FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC;



-- ============================================
-- 6. CUSTOMER RECENCY ANALYSIS
-- Purpose:
-- Measure how recently customers made purchases
-- ============================================

SELECT
    c.customer_unique_id,
    (CURRENT_DATE - MAX(o.order_purchase_timestamp)::date) AS recency_days
FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY recency_days ASC;



-- ============================================
-- 7. COMPLETE RFM ANALYSIS QUERY
-- Purpose:
-- Combine Recency, Frequency, and Monetary metrics
-- to evaluate customer behavior
-- ============================================

SELECT
    c.customer_unique_id,

    (CURRENT_DATE - MAX(o.order_purchase_timestamp)::date) AS recency_days,

    COUNT(DISTINCT o.order_id) AS frequency,

    SUM(oi.price) AS monetary

FROM olist_orders_dataset o

JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id

JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id

GROUP BY c.customer_unique_id;



-- ============================================
-- 8. TOP HIGH-VALUE CUSTOMERS
-- Purpose:
-- Identify customers contributing the highest revenue
-- ============================================

SELECT
    c.customer_unique_id,
    SUM(oi.price) AS total_revenue
FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_unique_id
ORDER BY total_revenue DESC
LIMIT 10;



-- ============================================
-- 9. REVENUE DISTRIBUTION ANALYSIS
-- Purpose:
-- Analyze overall revenue concentration patterns
-- ============================================

SELECT
    ROUND(SUM(price)::numeric, 2) AS total_revenue,
    ROUND(AVG(price)::numeric, 2) AS average_order_value,
    ROUND(MAX(price)::numeric, 2) AS highest_order_value
FROM olist_order_items_dataset;
